Description of descrambler_rx
Home > ubx-v2x > descrambler_rx.m
descrambler_rx
PURPOSE
DESCRAMBLER Bit descrambler
SYNOPSIS
function out = descrambler_rx(d_in)
DESCRIPTION
DESCRAMBLER Bit descrambler
   Authors: Ioannis Sarris, Sebastian Schiessl, u-blox
   contact email: ioannis.sarris@u-blox.com
   August 2018; Last revision: 04-December-2020
CROSS-REFERENCE INFORMATION
This function calls:
scrambler_tx SCRAMBLER Bit scrambler
This function is called by:
data_rx DATA_RX Receiver processing of all DATA OFDM symbols
ldpc_dec LDPC_DEC Decodes an LLR stream with LDPC decoding
SOURCE CODE
function out = descrambler_rx(d_in)
%DESCRAMBLER Bit descrambler
%
%   Authors: Ioannis Sarris, Sebastian Schiessl, u-blox
%   contact email: ioannis.sarris@u-blox.com
%   August 2018; Last revision: 04-December-2020
% Copyright (C) u-blox
%
% All rights reserved.
%
% Permission to use, copy, modify, and distribute this software for any
% purpose without fee is hereby granted, provided that this entire notice
% is included in all copies of any software which is or includes a copy
% or modification of this software and in all copies of the supporting
% documentation for such software.
%
% THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
% WARRANTY. IN PARTICULAR, NEITHER THE AUTHOR NOR U-BLOX MAKES ANY
% REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY
% OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR PURPOSE.
%
% Project: ubx-v2x
% Purpose: V2X baseband simulation model
persistent pn_seq
len = size(d_in, 1);
tmp_in = d_in(8:len, 1);
pn_seq = d_in(7:-1:1, 1);
% Perform scrambling (identical to descrabling)
[pn_seq, out] = scrambler_tx(tmp_in, pn_seq);
end