Description of dot11_fft
Home > ubx-v2x > dot11_fft.m
dot11_fft
PURPOSE
DOT11_FFT 802.11 FFT
SYNOPSIS
function out = dot11_fft(in, n_fft)
DESCRIPTION
DOT11_FFT 802.11 FFT
   Authors: Ioannis Sarris, Sebastian Schiessl, u-blox
   contact email: ioannis.sarris@u-blox.com
   August 2018; Last revision: 04-December-2020
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
chan_est CHAN_EST Channel estimation algorithm, using LTF preamble
data_rx DATA_RX Receiver processing of all DATA OFDM symbols
ngv_chan_est NGV_CHAN_EST Channel estimation algorithm, using NGV-LTF preamble
sig_pre_rx SIG_PRE_RX Get f-domain SIG messages (L-SIG, RL-SIG, NGV-SIG, RNGV-SIG) for preamble autodetection and as input to decoder
SOURCE CODE
function out = dot11_fft(in, n_fft)
%DOT11_FFT 802.11 FFT
%
%   Authors: Ioannis Sarris, Sebastian Schiessl, u-blox
%   contact email: ioannis.sarris@u-blox.com
%   August 2018; Last revision: 04-December-2020
% Copyright (C) u-blox
%
% All rights reserved.
%
% Permission to use, copy, modify, and distribute this software for any
% purpose without fee is hereby granted, provided that this entire notice
% is included in all copies of any software which is or includes a copy
% or modification of this software and in all copies of the supporting
% documentation for such software.
%
% THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
% WARRANTY. IN PARTICULAR, NEITHER THE AUTHOR NOR U-BLOX MAKES ANY
% REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY
% OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR PURPOSE.
%
% Project: ubx-v2x
% Purpose: V2X baseband simulation model
% FFT with shifting and normalization
in2 = fft(in, n_fft);
out = in2([n_fft/2 + 1:n_fft 1:n_fft/2], :);
end