Description of dot11_ifft
Home > ubx-v2x > dot11_ifft.m
dot11_ifft
PURPOSE
DOT11_IFFT 802.11 IFFT
SYNOPSIS
function out = dot11_ifft(in, n_fft)
DESCRIPTION
DOT11_IFFT 802.11 IFFT
   Authors: Ioannis Sarris, Sebastian Schiessl, u-blox
   contact email: ioannis.sarris@u-blox.com
   August 2018; Last revision: 04-December-2020
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
data_tx DATA_TX Transmitter processing of all DATA OFDM symbols
ltf_tx LTF_TX Generates LTF preamble
ngv_ltf_tx NGV_LTF_TX Generates NGV-LTF preamble
ngv_sig_tx NGV_SIG_TX NGV_SIG message transmitter/parser
ngv_stf_tx NGV_STF_TX Generates NGV-STF preamble
sig_tx SIG_TX SIG message transmitter/parser
stf_tx STF_TX Generates STF preamble
SOURCE CODE
function out = dot11_ifft(in, n_fft)
%DOT11_IFFT 802.11 IFFT
%
%   Authors: Ioannis Sarris, Sebastian Schiessl, u-blox
%   contact email: ioannis.sarris@u-blox.com
%   August 2018; Last revision: 04-December-2020
% Copyright (C) u-blox
%
% All rights reserved.
%
% Permission to use, copy, modify, and distribute this software for any
% purpose without fee is hereby granted, provided that this entire notice
% is included in all copies of any software which is or includes a copy
% or modification of this software and in all copies of the supporting
% documentation for such software.
%
% THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
% WARRANTY. IN PARTICULAR, NEITHER THE AUTHOR NOR U-BLOX MAKES ANY
% REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY
% OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR PURPOSE.
%
% Project: ubx-v2x
% Purpose: V2X baseband simulation model
% IFFT with shifting and normalization
idx = [(n_fft/2 + 1):n_fft, 1:(n_fft/2)];
out = n_fft*ifft(in(idx, :), n_fft);
end